nmpc_tau_node:
  ros__parameters:
    use_sim_time: true

    urdf_path: "/home/cyh/panda_ros2/src/panda_ros/model/panda_tau_sim.urdf"
    obstacle_config_path: "/home/cyh/panda_ros2/model/franka_emika_panda/static_sphere_obstacles.xml"
    scene_xml_path: "/home/cyh/panda_ros2/model/franka_emika_panda/scene_tau_ros.xml"
    ee_frame_name: "ee_center_body"

    joint_states_topic: "/joint_states"
    joint_trajectory_topic: "/global_joint_trajectory"
    nmpc_result_topic: "/nmpc_result"
    target_pose_topic: "/global_target_pose"

    target_x: 0.25
    target_y: 0.3
    target_z: 0.25
    target_qx: 1.0
    target_qy: 0.0
    target_qz: 0.0
    target_qw: 0.0

    use_global_trajectory: false

    ee_frame_pos_tolerance: 0.001
    ee_frame_rot_tolerance: 0.1
    ee_frame_lin_vel_tolerance: 0.02
    ee_frame_ang_vel_tolerance: 0.1

    sorr_pos_damping_ratio: 1.0
    sorr_pos_natural_frequency: 10.0
    sorr_pos_max_linear_velocity: 1.0
    sorr_pos_max_linear_acceleration: 10.0

    sorr_rot_damping_ratio: 1.0
    sorr_rot_natural_frequency: 10.0
    sorr_rot_max_angular_velocity: 0.7845
    sorr_rot_max_angular_acceleration: 0.7845

    trajectory_path_stage_spacing: 0.015

    nmpc_weights:
      stage:
        pos: [2500.0, 2500.0, 2500.0]
        rot: [100.0, 100.0, 100.0]
        ee_lin_vel: [5.0, 5.0, 5.0]
        ee_ang_vel: [2.0, 2.0, 2.0]
        q_reg: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
        dq_reg: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
        ddq_reg: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

      terminal:
        pos: [4000.0, 4000.0, 4000.0]
        rot: [200.0, 200.0, 200.0]
        ee_lin_vel: [10.0, 10.0, 10.0]
        ee_ang_vel: [4.0, 4.0, 4.0]
        q_reg: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
        dq_reg: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

      soft_constraint:
        stage:
          slack_linear: 10000.0
          slack_quadratic: 1000000.0
        terminal:
          slack_linear: 10000.0
          slack_quadratic: 1000000.0
